default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: til_development
  username: postgres
  password: postgres
  host: db
  port: 5432

test: &test
  <<: *default
  database: til_test<%=ENV['TEST_ENV_NUMBER']%>
  username: postgres
  password: postgres
  host: db
  port: 5432
cucumber:
  <<: *test

staging:
  <<: *default
  database: til_staging

production:
  <<: *default
  database: til_production

cucumber:
  <<: *test

cucumber:
  <<: *test
